applicationName: test
dbConfig:
  url: "jdbc:oracle:thin:login/pass@host:port/schema"
  driver: "oracle.jdbc.driver.OracleDriver"
  user: login
  password: password
  tables:
    - table1
    - table2
    - table3
  query: "CUSTOMER_ID=2"
kafkaConfig:
  host: "TEST:9092"
  inputTopic: input
  outputTopic: output
  groupid: "consumerGroup"
  truststoreLocation: String
  truststorePassword: String
  keystoreLocation: String
  keystorePassword: String
  keyPassword: String